### ISSUE TITLE
Deal with kinesis better

### ISSUE THREAD

**Issue by otfrom** [MastodonC/kixi.comms#31]
This PR: https://github.com/MastodonC/kixi.comms/pull/30

Swallows the exception and prevents any calling code from dealing with this or dying (allowing marathon to deal with restarting things). If it loses its connection to kinesis, it is probably better to let it crash given the marathon supervision.

**Comment by acron0** [comment]
Reverted in https://github.com/MastodonC/kixi.comms/pull/34
